apiVersion: v1 # versão da API do Kubernetes
kind: Pod # tipo do objeto que estamos criando
metadata: # metadados do Pod
  creationTimestamp: null
  labels: # labels do Pod
    run: giropops # label run com o valor giropops
  name: giropops # nome do Pod que estamos criando
spec: # especificação do Pod
  containers: # containers que estão dentro do Pod
  - image: nginx # imagem do container
    name: giropops # nome do container
    ports: # portas que estão sendo expostas pelo container
      - containerPort: 80 # porta 80 exposta pelo container
    resources:
      limits: # limites máximo de recursos que o container pode utilizar
        memory: "128Mi" #imite de memória que está sendo utilizado pelo container, no caso 128 megabytes no máximo 
        cpu: "0.5" # limite máxima de CPU que o container pode utilizar, no caso 50% de uma CPU no máximo
      requests: # recursos garantidos ao container
        memory: "64Mi" # memoria garantida ao container, no aso 64 megabytes
        cpu: "0.3" # CPU GARANTIDA AO CONTAINER, NO CASO 30% DE UMA CPU
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}